version: '3.8'

services:
  api:
    container_name: ${SERVICE_NAME}-api
    build:
      context: .
      target: api_prod
      args:
        - GITLAB_TOKEN
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - default

  db:
    container_name: ${SERVICE_NAME}-db
    restart: always
    image: postgres:15.2
    volumes:
      - ./build/package/sql/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - ${POSTGRES_OPEN_PORT-54322}:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB